version: "3.9"
services:
  webapp:
    build:
      context: .
    container_name: webapp
    ports:
      - "3000:3000"
  main:
    container_name: main
    build:
      context: /testjhon_backend/
    ports:
      - "5000:5000"
    restart: always